#!/usr/bin/env python

import pyinotify,os

class MyEventHandler(pyinotify.ProcessEvent):
    def process_IN_CLOSE_WRITE(self, event):
        print 'Reloading radiusd configuration.'
        os.system('systemctl reload radiusd')

def main():
    # watch manager
    wm = pyinotify.WatchManager()
    wm.add_watch('/var/lib/samba/private/smbpasswd', pyinotify.ALL_EVENTS, rec=True)

    # event handler
    eh = MyEventHandler()

    # notifier
    notifier = pyinotify.Notifier(wm, eh)
    notifier.loop()

if __name__ == '__main__':
    main()

